---
#Create Vm
#
- name: Create Azure VM
  hosts: "{{host}}"
  connection: local
  gather_facts: yes
  roles:
     - createvm
  tags:
    - createvm
 
#Stop the services

- name: "Stop {{web}} Service in Ansible host"
  hosts: "{{host}}"
  become: yes
  gather_facts: yes
  roles:
     - stop-service
  tags:
    - stop-service

#Restart the services

- name: "Start {{web}} Service in Ansible host"
  hosts: "{{host}}"
  become: yes
  gather_facts: yes
  roles:
     - start-service
  tags:
    - start-service

#Check the status of services
- name: "Start {{web}} Service in Ansible host"
  hosts: "{{host}}"
  become: yes
  gather_facts: yes
  roles:
     - status-service
  tags:
    - status-service

#APPLICATIONS
- name: "Check the some common application Versions"
  hosts: "{{host}}"
  become: yes
  gather_facts: yes
  roles:
     - application-status
  tags:
    - application-status

#Check some common web application service status
- name: "Check the some common application status"
  hosts: "{{host}}"
  become: yes
  gather_facts: yes
  roles:
     - web-services-status
  tags:
    - web-services-status

# Stop Vm Using Name
- name: "Check the some common application status"
  hosts: "{{host}}"
  connection: local
  roles:
     - stop-vm
  tags:
    - stop-vm

# Stop Vm Using Name
- name: "Check the some common application status"
  hosts: "{{host}}"
  connection: local
  roles:
     - start-vm
  tags:
    - start-vm
