---
# tasks file for up-pods
- name: "fetch pods status"
  command: "kubectl scale deployment/{{service}} --replicas=1"
  register: services_state

- debug:
    var: services_state
- name: "fetch pods status"
  command: "kubectl get pods"
  register: services_state

- debug:
    var: services_state
